require('@alipay/appx-compiler/lib/sjsEnvInit');
require('./config$');

require('../../node_modules/mini-antui/es/badge/index');
require('../../node_modules/mini-antui/es/tabs/index');
require('../../node_modules/mini-antui/es/tabs/tab-content/index');
require('../../node_modules/mini-antui/es/modal/index');
require('../../node_modules/mini-antui/es/am-checkbox/index');
require('../../components/count-down/index');
require('../../node_modules/mini-antui/es/input-item/index');
require('../../node_modules/mini-antui/es/list/index');
require('../../node_modules/mini-antui/es/list/list-item/index');
require('../../node_modules/mini-antui/es/picker-item/index');
require('../../node_modules/mini-antui/es/notice/index');
require('../../pages/index/index');
require('../../pages/diary/diary');
require('../../pages/mine/mine');
require('../../pages/calendar/calendar');
require('../../pages/schedule/schedule');
